### Get health status

GET /health-check HTTP/1.1
Host: localhost:8000

### Get active services

GET /active-apps HTTP/1.1
Host: localhost:8000

### Sets the active service

POST /active-apps/toggle?title=Masodon+Social+Platform&status=true HTTP/1.1
Host: localhost:5000

### Add an active Service

POST /active-apps HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "title": "service4"
}

### Delete an active service

DELETE /active-apps?title=service4 HTTP/1.1
Host: localhost:5000


