FROM python:3.8-slim-buster

WORKDIR /managment-app

COPY backend backend
COPY frontend/build/web frontend/build/web

COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN pip install waitress

WORKDIR /managment-app/backend
RUN pip install waitress

CMD ["waitress-serve", "--listen=*:8000", "api:app"]